level_0 = {
    'terrain': 'levels/level_data/0/level0_terrain.csv',
    'terrain_bg': 'levels/level_data/0/level0_terrain_bg.csv',
    'coins': 'levels/level_data/0/level0_coins.csv',
    'fg palms': 'levels/level_data/0/level0_fg_palms.csv',
    'bg palms': 'levels/level_data/0/level0_bg_palms.csv',
    'crates': 'levels/level_data/0/level0_crates.csv',
    'enemies': 'levels/level_data/0/level0_enemies.csv',
    'player': 'levels/level_data/0/level0_player.csv',
    'grass': 'levels/level_data/0/level0_grass.csv',
    'constraint': 'levels/level_data/0/level0_constrains.csv',
    'ladder': 'levels/level_data/0/level0_ladder.csv',
    'masonry': 'levels/level_data/0/level0_masonry.csv',
    'masonry_collide': 'levels/level_data/0/level0_masonry_collide.csv',
    'door': 'levels/level_data/0/level0_door.csv',
    'terrain_masonry': 'levels/level_data/0/level0_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/0/level0_decoration_masonry.csv',
    'npc': 'levels/level_data/0/level0_npc.csv',
    'village': 'levels/level_data/0/level0_village.csv',
    'node_pos':(100,400),
	'unlock':1,
	'node_graphics': 'graphics/overworld/0'}

level_1 = {
    'terrain': 'levels/level_data/1/level1_terrain.csv',
    'coins': 'levels/level_data/1/level1_coins.csv',
    'fg palms': 'levels/level_data/1/level1_fg_palms.csv',
    'bg palms': 'levels/level_data/1/level1_bg_palms.csv',
    'crates': 'levels/level_data/1/level1_crates.csv',
    'enemies': 'levels/level_data/1/level1_enemies.csv',
    'player': 'levels/level_data/1/level1_player.csv',
    'grass': 'levels/level_data/1/level1_grass.csv',
    'constraint': 'levels/level_data/1/level1_constrains.csv',
    'ladder': 'levels/level_data/1/level1_ladder.csv',
    'masonry': 'levels/level_data/1/level1_masonry.csv',
    'masonry_collide': 'levels/level_data/1/level1_masonry_collide.csv',
    'door': 'levels/level_data/1/level1_door.csv',
    'terrain_masonry': 'levels/level_data/1/level1_terrain_masonry.csv',
   'decoration_masonry': 'levels/level_data/1/level1_decoration_masonry.csv',
    'node_pos':(260,220),
	'unlock':2,
	'node_graphics': 'graphics/overworld/1'}

level_2 = {
    'terrain': 'levels/level_data/0/level0_terrain.csv',
    'coins': 'levels/level_data/0/level0_coins.csv',
    'fg palms': 'levels/level_data/0/level0_fg_palms.csv',
    'bg palms': 'levels/level_data/0/level0_bg_palms.csv',
    'crates': 'levels/level_data/0/level0_crates.csv',
    'enemies': 'levels/level_data/0/level0_enemies.csv',
    'player': 'levels/level_data/0/level0_player.csv',
    'grass': 'levels/level_data/0/level0_grass.csv',
    'constraint': 'levels/level_data/0/level0_constrains.csv',
    'ladder': 'levels/level_data/0/level0_ladder.csv',
    'masonry': 'levels/level_data/0/level0_masonry.csv',
    'masonry_collide': 'levels/level_data/0/level0_masonry_collide.csv',
    'door': 'levels/level_data/0/level0_door.csv',
    'terrain_masonry': 'levels/level_data/0/level0_terrain_masonry.csv',
    #'decoration_masonry': 'levels/level_data/0/level0_decoration_masonry.csv',
    'node_pos':(260,100),
	'unlock':3,
	'node_graphics': 'graphics/overworld/2'}

level_3 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(410,100),
	'unlock':4,
	'node_graphics': 'graphics/overworld/2'}

level_4 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(410,500),
	'unlock':5,
	'node_graphics': 'graphics/overworld/2'}

level_5 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(610,620),
	'unlock':6,
	'node_graphics': 'graphics/overworld/2'}

level_6 ={
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(610,350),
	'unlock':7,
	'node_graphics': 'graphics/overworld/2'}

level_7 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(610,100),
	'unlock':8,
	'node_graphics': 'graphics/overworld/2'}

level_8 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(810,350),
	'unlock':9,
	'node_graphics': 'graphics/overworld/2'}

level_9 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(810,500),
	'unlock':10,
	'node_graphics': 'graphics/overworld/2'}

level_10 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'node_pos':(1000,500),
	'unlock':0,
	'node_graphics': 'graphics/overworld/2'}

level_11 = {
    'terrain': 'levels/level_data/001/level001_terrain.csv',
    'coins': 'levels/level_data/001/level001_coins.csv',
    'fg palms': 'levels/level_data/001/level001_fg_palms.csv',
    'bg palms': 'levels/level_data/001/level001_bg_palms.csv',
    'crates': 'levels/level_data/001/level001_crates.csv',
    'enemies': 'levels/level_data/001/level001_enemies.csv',
    'player': 'levels/level_data/001/level001_player.csv',
    'grass': 'levels/level_data/001/level001_grass.csv',
    'constraint': 'levels/level_data/001/level001_constrains.csv',
    'ladder': 'levels/level_data/001/level001_ladder.csv',
    'masonry': 'levels/level_data/001/level001_masonry.csv',
    'masonry_collide': 'levels/level_data/001/level001_masonry_collide.csv',
    'door': 'levels/level_data/001/level001_door.csv',
    'terrain_masonry': 'levels/level_data/001/level001_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/001/level001_decoration_masonry.csv',
    'npc': 'levels/level_data/001/level001_npc.csv',
    'node_pos':(810,-500),
	'unlock':0,
	'node_graphics': 'graphics/overworld/1'}
level_12 = {
    'terrain': 'levels/level_data/002/level002_terrain.csv',
    'coins': 'levels/level_data/002/level002_coins.csv',
    'fg palms': 'levels/level_data/002/level002_fg_palms.csv',
    'bg palms': 'levels/level_data/002/level002_bg_palms.csv',
    'crates': 'levels/level_data/002/level002_crates.csv',
    'enemies': 'levels/level_data/002/level002_enemies.csv',
    'player': 'levels/level_data/002/level002_player.csv',
    'grass': 'levels/level_data/002/level002_grass.csv',
    'constraint': 'levels/level_data/002/level002_constrains.csv',
    'ladder': 'levels/level_data/002/level002_ladder.csv',
    'masonry': 'levels/level_data/002/level002_masonry.csv',
    'masonry_collide': 'levels/level_data/002/level002_masonry_collide.csv',
    'door': 'levels/level_data/002/level002_door.csv',
    'terrain_masonry': 'levels/level_data/002/level002_terrain_masonry.csv',
    'decoration_masonry': 'levels/level_data/002/level002_decoration_masonry.csv',
    'node_pos':(810,-500),
	'unlock':0,
	'node_graphics': 'graphics/overworld/1'}


levels = {
	0: level_0,
	1: level_1,
	2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
    6: level_6,
    7: level_7,
    8: level_8,
    9: level_9,
    10: level_10,
    11: level_11,
    12: level_12,
}

text_path = 'data/speaks.txt'
font_path = 'graphics/ui/ARCADEPI.TTF'

sound_level = ['audio/level_1.mp3', 'audio/level_1.mp3', 'audio/level_1.mp3', '', '', '', '', '', '', 'audio/level_0.mp3','audio/level_0.mp3','audio/level_0.mp3']